#!/usr/bin/env bash

# This file is a wrapper for "$CURRENT_SCRIPT-wrapped.sh".
# It asks the user to prove sudo rights before it runs.

# see https://stackoverflow.com/a/246128/5354298
get_script_dir() { echo "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; }
SCRIPT_DIR=$(get_script_dir)
CURRENT_SCRIPT="$(basename "$0")"

if sudo -S echo 'sudo rights confirmed'
then
    "$SCRIPT_DIR/$CURRENT_SCRIPT-wrapped.sh" "$@"
fi
